#!/bin/sh

DAEMON="px4"
RUN_SCRIPT="/home/px4/run.sh"

case "$1" in
    start)
	echo "Starting $DAEMON..."
	if [ -f "$RUN_SCRIPT" ]; then
	    chmod +x "$RUN_SCRIPT"
	    exec "$RUN_SCRIPT"
	    sleep 2
	else
            echo "FAIL: $RUN_SCRIPT not found"
	fi
	;;
    stop|restart) ;;
esac

exit 0
