#!/bin/sh

DAEMON="px4"
PX4_DIR="/home/px4"
RUN_SCRIPT="$PX4_DIR/run.sh"

case "$1" in
    start)
	echo "Starting $DAEMON..."
	if [ -f "$RUN_SCRIPT" ]; then
	    chmod +x "$RUN_SCRIPT"
	    cd "$PX4_DIR"
	    exec "$RUN_SCRIPT"
	    sleep 2
	else
            echo "FAIL: $RUN_SCRIPT not found"
	fi
	;;
    stop|restart) ;;
esac

exit 0
